### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by shohre10539** [inception-project/external-recommender-spacy#5]
Hi,

I am trying to use this remote-recommender I keep getting this error:

ERROR [SYSTEM] RecommendationServiceImpl - Error applying recommender [Spacy_NER](2) for user [admin] to document [fileName.txt](431) in project [ProjectName](2) - skipping recommender

How can I debug this?
Thanks,

**Comment by jcklie** [comment]
What URL are you specifying in INCEpTION?

**Comment by shohre10539** [comment]
http://0.0.0.0:5000/

**Comment by shohre10539** [comment]
I get this error on the flask server: "POST /predict HTTP/1.1" 404 -"

**Comment by jcklie** [comment]
Thank you for your interest! You need to use either http://0.0.0.0:5000/ner or http://0.0.0.0:5000/pos I think . I admit that it is not documented. I will deprecate this project soon in favor of the more general https://github.com/inception-project/inception-external-recommender .

**Comment by shohre10539** [comment]
Perfect, it's working now.
Ok thanks , I will also switch to the new one. :)
